---
- name: "check OS version"
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Check Version ond Device
      routeros_command:
        commands: /system package print
      register: version_output
      
    - name: Display facts variables
      debug:
        var: version
