---
- hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Disable Telnet and Enable SSH
    network_cli:
      command: "/ip service set telnet disabled=yes; /ip service set ssh disabled=no"
